apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: darkreach
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  MR_ROUNDS: {{ .Values.worker.mrRounds | quote }}
  SIEVE_LIMIT: {{ .Values.worker.sieveLimit | quote }}
  PRST_MIN_DIGITS: {{ .Values.worker.prstMinDigits | quote }}
  PFGW_MIN_DIGITS: {{ .Values.worker.pfgwMinDigits | quote }}
  LOG_FORMAT: "json"
