apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-coordinator
  labels:
    app.kubernetes.io/name: darkreach
    app.kubernetes.io/component: coordinator
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.coordinator.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: darkreach
    app.kubernetes.io/component: coordinator
    app.kubernetes.io/instance: {{ .Release.Name }}
